import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {branch,straight} from '../../src/examples.mjs';import {compile,createSession,parseSession,validateSession} from '../../src/core.mjs';
const out='tests/browser/artifacts';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,chromiumSandbox:true});
const completed=[],errors=[];const base=process.env.BASE_URL||'http://127.0.0.1:4173';
const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
page.on('dialog',dialog=>dialog.dismiss());
const step=async(name,fn)=>{await fn();completed.push(name);console.log(`PASS ${name}`);};
const ack=async()=>{await page.locator('#ack').check();await expect(page.locator('#ack')).toBeChecked();await expect(page.locator('[data-export="json"]')).toBeEnabled();};
const assertVisible=async(locator)=>expect(locator).toBeVisible();
async function exportFile(ext,basename='sample'){const wait=page.waitForEvent('download');await page.locator(`[data-export="${ext}"]`).click();const download=await wait;const path=`${out}/${basename}.${ext}`;await download.saveAs(path);return readFile(path,'utf8');}
try{
await step('Japanese initial render and full pair accounting',async()=>{
 await page.goto(base);await page.locator('#checklist .pair-card').first().waitFor();await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('.pair-card')).toHaveCount(21);await expect(page.locator('#stats')).toContainText(/21/);await expect(page.locator('[data-result="0"]')).toBeDisabled();await page.screenshot({path:`${out}/desktop-ja.png`,fullPage:true});
});
await step('keyboard skip link, language switch, scope acknowledgement',async()=>{
 await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#workspace')).toBeFocused();await page.locator('[data-lang="en"]').click();assert.equal(await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(el=>el.id);return new Set(ids).size===ids.length;}),true);await page.locator('.reference summary').click();await expect(page.locator('#reference svg')).toHaveAccessibleName(/Bench sample/);await page.locator('.reference summary').click();await ack();await expect(page.locator('[data-result="0"]')).toBeEnabled();
});
await step('manual pass, fail, skipped and note records',async()=>{
 await page.locator('[data-result="0"]').selectOption('pass');await page.locator('[data-note="0"]').fill('Synthetic observation');await page.locator('[data-note="0"]').press('Tab');await page.locator('[data-result="1"]').selectOption('fail');await page.locator('[data-result="2"]').selectOption('skipped');await expect(page.locator('#progress-count')).toContainText(/3 \/ 21/);await expect(page.locator('#status-counts')).toContainText(/User pass 1/);
});
await step('filters, empty state, search and reset cancellation',async()=>{
 await page.locator('#filter').selectOption('problem');await expect(page.locator('.pair-card')).toHaveCount(2);await page.locator('#filter').selectOption('pending');await expect(page.locator('.pair-card')).toHaveCount(18);await page.locator('[data-result="3"]').focus();await page.locator('[data-result="3"]').selectOption('pass');await expect(page.locator('.pair-card')).toHaveCount(17);await expect(page.locator('#showing')).toContainText('17 / 21');await expect(page.locator('[data-result="4"]')).toBeFocused();await page.locator('#filter').selectOption('all');await page.locator('[data-result="3"]').selectOption('untested');await page.locator('#filter').selectOption('problem');await page.locator('[data-result="1"]').selectOption('pass');await expect(page.locator('.pair-card')).toHaveCount(1);await page.locator('[data-result="2"]').selectOption('pass');await expect(page.locator('.pair-card')).toHaveCount(0);await page.locator('#filter').selectOption('all');await page.locator('[data-result="1"]').selectOption('fail');await page.locator('[data-result="2"]').selectOption('skipped');await page.locator('#filter').selectOption('pending');await page.locator('#search').fill('absent');await assertVisible(page.locator('.empty'));await page.locator('#search').fill('');await page.locator('#filter').selectOption('all');await page.locator('#reset').click();await assertVisible(page.locator('#confirm-dialog'));await page.keyboard.press('Escape');await expect(page.locator('#confirm-dialog')).not.toBeVisible();await expect(page.locator('#progress-count')).toContainText(/3 \/ 21/);
});
await step('all four actual exports and versioned JSON record round-trip',async()=>{
 const json=await exportFile('json'),saved=parseSession(json);assert.equal(saved.results[0].status,'pass');assert.equal(saved.results[0].note,'Synthetic observation');assert.equal(saved.results[1].status,'fail');const csv=await exportFile('csv');assert.equal(csv.split('\r\n').filter(Boolean).length,22);const svg=await exportFile('svg');assert.ok(svg.startsWith('<svg'));const html=await exportFile('html');assert.match(html,/User-recorded results only/);const report=await context.newPage();await report.setContent(html);await expect(report.locator('tbody tr')).toHaveCount(21);await report.emulateMedia({media:'print'});await report.pdf({path:`${out}/print-report.pdf`,format:'A4',printBackground:true});await report.screenshot({path:`${out}/print-preview.png`,fullPage:true});await report.close();
 await page.locator('#file').setInputFiles({name:'session.json',mimeType:'application/json',buffer:Buffer.from(json)});await page.locator('#dialog-confirm').click();await expect(page.locator('#confirm-dialog')).not.toBeVisible();await expect(page.locator('#ack')).not.toBeChecked();await ack();await expect(page.locator('#progress-count')).toContainText(/3 \/ 21/);
});
await step('editing locks stale records; cancellation retains them; changed map resets all',async()=>{
 await page.locator('#title').fill('Revised synthetic kit');await expect(page.locator('[data-result="0"]')).toBeDisabled();await expect(page.locator('[data-export="json"]')).toBeDisabled();await page.locator('#compile').click();await page.locator('#confirm-dialog button[value="cancel"]').click();await expect(page.locator('#confirm-dialog')).not.toBeVisible();await assertVisible(page.locator('#dirty'));await expect(page.locator('#progress-count')).toContainText(/3 \/ 21/);await page.locator('#compile').click();await page.locator('#dialog-confirm').click();await expect(page.locator('#confirm-dialog')).not.toBeVisible();await expect(page.locator('#progress-count')).toContainText(/0 \/ 21/);await expect(page.locator('[data-note="0"]')).toHaveValue('');
});
await step('invalid JSON never replaces valid work; mode-switch and repeated generation',async()=>{
 await page.locator('#json-tab').click();const valid=await page.locator('#json-input').inputValue();await page.locator('#json-input').fill('{"schema":"probeplan.pinmap.v1","schema":"duplicate"}');await page.locator('#compile').click();await expect(page.locator('#notice')).toContainText(/duplicate key/);await expect(page.locator('[data-export="json"]')).toBeDisabled();await page.locator('#table-tab').click();await expect(page.locator('#json-input')).toBeVisible();await page.locator('#json-input').fill(valid);await page.locator('#compile').click();await expect(page.locator('#notice')).toContainText(/unchanged/);await page.locator('#compile').click();await expect(page.locator('.pair-card')).toHaveCount(21);await page.locator('#table-tab').click();
});
await step('invalid table allocation and repeated add/remove',async()=>{
 await page.locator('[data-field="net"][data-row="0"]').fill('ONLY_ONE');await page.locator('#compile').click();await expect(page.locator('#notice')).toContainText(/at least two/);await page.locator('[data-field="net"][data-row="0"]').fill('LINE_A');await page.locator('#compile').click();await page.locator('#add').click();await expect(page.locator('#pin-rows tr')).toHaveCount(8);await page.locator('[data-remove="7"]').click();await expect(page.locator('#pin-rows tr')).toHaveCount(7);await page.locator('#compile').click();
});
await step('device save, reload/restore, cancelled deletion then confirmed deletion',async()=>{
 await page.locator('[data-result="0"]').selectOption('pass');await page.locator('#save').click();await expect(page.locator('#restore')).toBeEnabled();await page.reload();await page.locator('[data-lang="en"]').click();await expect(page.locator('#progress-count')).toContainText(/0 \/ 21/);await page.locator('#restore').click();await expect(page.locator('#progress-count')).toContainText(/1 \/ 21/);await ack();await page.locator('#forget').click();await page.keyboard.press('Escape');await expect(page.locator('#confirm-dialog')).not.toBeVisible();await expect(page.locator('#restore')).toBeEnabled();await page.locator('#forget').click();await page.locator('#dialog-confirm').click();await expect(page.locator('#confirm-dialog')).not.toBeVisible();await expect(page.locator('#restore')).toBeDisabled();
});
await step('same file can be imported twice and malformed import is non-destructive',async()=>{
 const obj=createSession(compile(straight)),buffer=Buffer.from(JSON.stringify(obj));for(let i=0;i<2;i++){await page.locator('#file').setInputFiles({name:'repeat.json',mimeType:'application/json',buffer});await page.locator('#dialog-confirm').click();await expect(page.locator('#confirm-dialog')).not.toBeVisible();await expect(page.locator('#ack')).not.toBeChecked();await expect(page.locator('.pair-card')).toHaveCount(6);await expect(page.locator('#progress-count')).toContainText('0 / 6');if(i===0){await ack();await page.locator('[data-result="0"]').selectOption('pass');}}await page.locator('#file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await expect(page.locator('#notice')).toContainText(/JSON/);await expect(page.locator('.pair-card')).toHaveCount(6);await ack();
});
await step('desktop and responsive layouts contain no viewport overflow',async()=>{
 await page.locator('#compile').click();await expect(page.locator('#notice')).toContainText(/unchanged/);await page.screenshot({path:`${out}/desktop-en.png`,fullPage:true});for(const width of [768,390,320]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow at ${width}`);await page.screenshot({path:`${out}/mobile-${width}.png`,fullPage:true});}await page.setViewportSize({width:1440,height:1050});
});
await step('maximum pin plan and reference labels',async()=>{
 const max={schema:'probeplan.pinmap.v1',title:'Maximum synthetic example',connectors:[{id:'A',label:'Labels only',pins:Array.from({length:32},(_,i)=>String(i+1))}],nets:[],unused:Array.from({length:32},(_,i)=>({connector:'A',pin:String(i+1)}))};await page.locator('#file').setInputFiles({name:'max.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(max))});await expect(page.locator('.pair-card')).toHaveCount(496);await ack();assert.equal(parseSession(await exportFile('json','maximum')).results.length,496);await page.locator('.reference summary').click();await assertVisible(page.locator('#reference svg'));await page.locator('#filter').selectOption('connected');await expect(page.locator('.pair-card')).toHaveCount(0);await page.locator('#filter').selectOption('all');
});
await step('wide ASCII/CJK SVG reference stays inside its label columns',async()=>{
 const map=structuredClone(straight);map.title='W'.repeat(60);map.connectors[0].label='W'.repeat(40);map.connectors[0].pins[0]='W'.repeat(20);map.nets[0].pins[0].pin='W'.repeat(20);map.nets[0].id='W'.repeat(24);map.connectors[1].label='端'.repeat(48);map.connectors[1].pins[0]='端'.repeat(24);map.nets[0].pins[1].pin='端'.repeat(24);await page.locator('#file').setInputFiles({name:'wide.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(map))});await expect(page.locator('.pair-card')).toHaveCount(6);await ack();await page.locator('.reference summary').click();const measurements=[];for(const [text,width] of [['W'.repeat(60),936],['W'.repeat(40),410],['W'.repeat(20),165],['W'.repeat(24),188],['端'.repeat(48),410],['端'.repeat(24),165]]){const labels=page.locator('#reference svg text').filter({hasText:new RegExp('^'+text+'$')});assert.ok(await labels.count()>0,`Missing SVG label: ${text}`);for(const label of await labels.all()){const measured=await label.evaluate(el=>({text:el.textContent,bboxWidth:el.getBBox().width,computedTextLength:el.getComputedTextLength(),fontSize:getComputedStyle(el).fontSize,fontFamily:getComputedStyle(el).fontFamily,fontAttribute:el.getAttribute('font-size'),fontFitWidth:el.getAttribute('data-fit-width'),textLengthAttribute:el.getAttribute('textLength')}));measurements.push({...measured,maximumWidth:width});}}await writeFile(`${out}/wide-label-measurements.json`,JSON.stringify(measurements,null,2));await writeFile(`${out}/wide-reference.svg`,await page.locator('#reference svg').evaluate(el=>el.outerHTML));await page.locator('#reference').screenshot({path:`${out}/wide-label-reference.png`});for(const measured of measurements)assert.ok(measured.bboxWidth<=measured.maximumWidth+2,`SVG label exceeded its column: ${JSON.stringify(measured)}`);
});
await step('direct screen print warns about filtered and unapplied content',async()=>{
 await page.locator('#filter').selectOption('connected');await expect(page.locator('.pair-card')).toHaveCount(2);await page.locator('#title').fill('Unapplied print draft');await page.emulateMedia({media:'print'});await expect(page.locator('.screen-print-note')).toBeVisible();await expect(page.locator('.scope')).toBeVisible();await expect(page.locator('#print-state')).toContainText('Unapplied edits');await expect(page.locator('#showing')).toContainText('2 / 6');await page.screenshot({path:`${out}/partial-screen-print.png`,fullPage:true});await page.pdf({path:`${out}/partial-screen-print.pdf`,format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});
});
await step('blocked storage is a visible recoverable error',async()=>{
 const isolated=await browser.newContext();await isolated.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Unavailable','SecurityError');};});const p=await isolated.newPage();await p.goto(base);await p.locator('[data-lang="en"]').click();await p.locator('#ack').check();await p.locator('#save').click();await expect(p.locator('#notice')).toContainText(/storage is unavailable/);await expect(p.locator('[data-export="json"]')).toBeEnabled();await isolated.close();
});
await step('no external application requests and no uncaught errors',async()=>{
 const observed=[];const p=await context.newPage();p.on('request',r=>observed.push(r.url()));await p.goto(base);await p.locator('#checklist .pair-card').first().waitFor();assert.ok(observed.every(url=>url.startsWith(base+'/')));await p.close();assert.deepEqual(errors,[]);
});
await writeFile(`${out}/results.json`,JSON.stringify({status:'passed',chromiumSandbox:true,checks:completed,uncaughtErrors:errors},null,2));
}catch(error){await page.screenshot({path:`${out}/failure.png`,fullPage:true}).catch(()=>{});await writeFile(`${out}/results.json`,JSON.stringify({status:'failed',chromiumSandbox:true,checks:completed,error:String(error),uncaughtErrors:errors},null,2));throw error;}finally{await context.close();await browser.close();}
