import {compile,validateSession,summarize,referenceCode,pinKey} from './core.mjs';
export const escapeMarkup = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export const escapeCSV = value => { const s=String(value), protectedValue=/^[\s]*[=+@-]/.test(s) ? "'"+s:s; return '"'+protectedValue.replaceAll('"','""')+'"'; };
const labels = {
  en:{scope:'Only isolated, disconnected wire-only passive assemblies. No mains, batteries, components or safety-critical use.',proof:'User-recorded results only. No measured evidence, electrical certification, thresholds, or hardware control.',diagram:'Pin reference · logical grouping, NOT connector face orientation',unused:'ISOLATED',connected:'CONNECTED',other:'NOT CONNECTED',untested:'Untested',pass:'User pass',fail:'User fail',skipped:'Skipped',manual:'Manual check record',expect:'Expected',result:'User record',note:'Note',pair:'Pair',pins:'Declared pins',net:'Net',blank:'No record',status:'Recording summary',full:'Full all-pairs plan',ref:'Map reference',version:'ProbePlan format v1',print:'Print this document using your browser. No links or scripts are required.'},
  ja:{scope:'完全に切り離された、配線のみの無通電アセンブリ専用。商用電源・電池・部品・安全に関わる用途には使用不可。',proof:'結果は手入力の記録です。実測の証拠・電気的な認証・しきい値の設定・機器制御は提供しません。',diagram:'ピン参照表 · 論理グループです。コネクタ正面の向きは示しません',unused:'単独・未接続',connected:'接続あり',other:'接続なし',untested:'未記録',pass:'手入力：一致',fail:'手入力：不一致',skipped:'スキップ',manual:'手動チェック記録',expect:'期待する関係',result:'手入力結果',note:'メモ',pair:'ペア',pins:'宣言ピン',net:'ネット',blank:'記録なし',status:'記録の概要',full:'全ペアの確認リスト',ref:'マップ参照',version:'ProbePlan 形式 v1',print:'ブラウザの印刷機能で印刷できます。外部リンク・スクリプトは不要です。'}
};
// Normal labels keep their typography. For long labels, explicit SVG geometry
// bounds fallback-font glyphs instead of trusting a font-metric estimate alone.
const fit = (value,width,font=12) => {
  const fitted=value.length*font*1.1>width;
  return ` font-size="${Math.min(font,width/(value.length*1.1)).toFixed(3)}"${fitted ? ` textLength="${width}" lengthAdjust="spacingAndGlyphs"` : ''} data-fit-width="${width}"`;
};
const lex = language => Object.hasOwn(labels,language) ? labels[language] : labels.en;
export function toJSON(input) { return JSON.stringify(validateSession(input),null,2)+'\n'; }
export function toCSV(input) {
  const s=validateSession(input),p=compile(s.map),r=new Map(s.results.map(r=>[r.pairId,r]));
  const rows=[['plan_title','map_reference','pair_number','connector_a','pin_a','connector_b','pin_b','expected','user_recorded_status','note','limitations']];
  for(const [i,pair] of p.pairs.entries()) { const result=r.get(pair.id); rows.push([s.map.title,referenceCode(s.binding),i+1,pair.a.connector,pair.a.pin,pair.b.connector,pair.b.pin,pair.expected,result.status,result.note,'Manual record; not measured evidence or electrical certification. Disconnected wire-only passive assemblies only.']); }
  return rows.map(row=>row.map(escapeCSV).join(',')).join('\r\n')+'\r\n';
}
export function toSVG(input,language='en') {
  const s=validateSession(input),t=lex(language),e=escapeMarkup;
  const membership=new Map(s.map.nets.flatMap(n=>n.pins.map(p=>[pinKey(p),n.id])));
  const positions=[174,174],cards=[];
  s.map.connectors.forEach((c,index)=>{
    const column=index%2,x=32+column*486,y=positions[column],h=94+c.pins.length*33; positions[column]+=h+20;
    cards.push(`<g><rect x="${x}" y="${y}" width="454" height="${h}" rx="12" fill="#ffffff" stroke="#c6d2cc"/><text x="${x+20}" y="${y+28}" font-weight="700"${fit(c.id,410,18)}>${e(c.id)}</text><text x="${x+20}" y="${y+50}" ${fit(c.label,410)}>${e(c.label)}</text><text x="${x+20}" y="${y+75}" font-size="11" fill="#53675d">PIN</text><text x="${x+226}" y="${y+75}" font-size="11" fill="#53675d">${e(t.net)}</text>${c.pins.map((pin,i)=>`<g><line x1="${x+20}" x2="${x+434}" y1="${y+86+i*33}" y2="${y+86+i*33}" stroke="#e4eae5"/><circle cx="${x+25}" cy="${y+104+i*33}" r="4" fill="${membership.has(pinKey({connector:c.id,pin}))?'#146749':'#8d978f'}"/><text x="${x+42}" y="${y+109+i*33}" ${fit(pin,165)}>${e(pin)}</text><text x="${x+226}" y="${y+109+i*33}" ${fit(membership.get(pinKey({connector:c.id,pin})) ?? t.unused,188)}>${e(membership.get(pinKey({connector:c.id,pin})) ?? t.unused)}</text></g>`).join('')}</g>`);
  });
  const height=Math.max(...positions)+30;
  // Fitted labels retain every character; short labels do not receive textLength.
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 ${height}" role="img" aria-labelledby="probeplan-reference-title probeplan-reference-desc"><title id="probeplan-reference-title">${e(s.map.title)} — ${e(t.diagram)}</title><desc id="probeplan-reference-desc">${e(t.scope)} ${e(t.proof)}</desc><rect width="1000" height="${height}" fill="#f4f6ef"/><g font-family="Arial, sans-serif" fill="#163e2e"><text x="32" y="35" font-size="14" font-weight="700">PROBEPLAN / ${e(referenceCode(s.binding))}</text><text x="32" y="68" ${fit(s.map.title,936,22)}>${e(s.map.title)}</text><text x="32" y="94" font-size="13">${e(t.diagram)}</text><text x="32" y="121" font-size="11">${e(t.scope)}</text><text x="32" y="144" font-size="11">${e(t.proof)}</text>${cards.join('')}</g></svg>\n`;
}
export function toHTML(input,language='en') {
  const s=validateSession(input),p=compile(s.map),t=lex(language),e=escapeMarkup,c=summarize(s),r=new Map(s.results.map(r=>[r.pairId,r]));
  return `<!doctype html><html lang="${language==='ja'?'ja':'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:"><title>ProbePlan · ${e(s.map.title)}</title><style>body{font:14px/1.5 Arial,sans-serif;max-width:1000px;margin:30px auto;padding:0 20px;color:#173d2e}h1{overflow-wrap:anywhere}.warning{border:2px solid #846026;padding:12px;background:#fff7e7}table{width:100%;border-collapse:collapse;font-size:12px}td,th{border:1px solid #a7b8ae;padding:8px;text-align:left;overflow-wrap:anywhere}td{max-width:220px}thead{display:table-header-group}tr{break-inside:avoid}svg{max-width:100%;height:auto}.summary{padding:12px;border:1px solid #a7b8ae}.reference{break-before:page}@page{size:A4;margin:13mm}@media print{body{margin:0;padding:0;font-size:11px}h1{font-size:22px}.warning{background:white}table{font-size:10px}td,th{padding:5px}.reference svg{width:100%;max-height:255mm}a{color:inherit}}</style></head><body><header><p>PROBEPLAN · ${e(t.version)} · ${e(t.ref)}: ${referenceCode(s.binding)}</p><h1>${e(s.map.title)}</h1><p>${e(t.full)} · ${p.pairs.length} pairs / ${s.map.connectors.reduce((n,c)=>n+c.pins.length,0)} pins</p></header><div class="warning"><strong>${e(t.scope)}</strong><p>${e(t.proof)}</p></div><h2>${e(t.status)}</h2><p class="summary">${e(t.untested)}: ${c.untested} · ${e(t.pass)}: ${c.pass} · ${e(t.fail)}: ${c.fail} · ${e(t.skipped)}: ${c.skipped}</p><h2>${e(t.manual)}</h2><p>${e(t.print)}</p><table><thead><tr><th>#</th><th>${e(t.pair)} A</th><th>${e(t.pair)} B</th><th>${e(t.expect)}</th><th>${e(t.result)}</th><th>${e(t.note)}</th></tr></thead><tbody>${p.pairs.map((pair,i)=>{const v=r.get(pair.id);return `<tr><td>${i+1}</td><td>${e(pair.a.connector)} / ${e(pair.a.pin)}</td><td>${e(pair.b.connector)} / ${e(pair.b.pin)}</td><td>${e(pair.expected==='connected'?t.connected:t.other)}</td><td>${e(t[v.status])}</td><td>${e(v.note)||'________________'}</td></tr>`;}).join('')}</tbody></table><section class="reference"><h2>${e(t.pins)}</h2>${toSVG(s,language)}</section></body></html>\n`;
}
